import http.server
import socketserver
import json
import subprocess
import os
import time
import threading

PORT = 8080
DIRECTORY = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(DIRECTORY, ".."))
sim_process = None

class SimulationHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=DIRECTORY, **kwargs)

    def do_POST(self):
        global sim_process
        if self.path == '/api/start':
            if sim_process is None or sim_process.poll() is not None:
                exe_path = os.path.join(PROJECT_ROOT, "build", "CarbonGrid.exe")
                if os.path.exists(exe_path):
                    # Start the C++ simulation in the background
                    sim_process = subprocess.Popen([exe_path], cwd=PROJECT_ROOT)
                    self.send_json_response({"status": "started"})
                else:
                    self.send_json_response({"error": "Executable not found. Build first."}, 404)
            else:
                self.send_json_response({"status": "already_running"})
        elif self.path == '/api/stop':
            if sim_process and sim_process.poll() is None:
                sim_process.terminate()
                self.send_json_response({"status": "stopped"})
            else:
                self.send_json_response({"status": "not_running"})
        else:
            self.send_error(404)

    def do_GET(self):
        global sim_process
        if self.path == '/api/status':
            is_running = sim_process is not None and sim_process.poll() is None
            self.send_json_response({"running": is_running})
        elif self.path == '/api/data':
            # Serve the live metrics JSON generated by C++
            data_file = os.path.join(DIRECTORY, "data", "metrics.json")
            if os.path.exists(data_file):
                with open(data_file, 'r') as f:
                    try:
                        data = json.load(f)
                        self.send_json_response(data)
                    except:
                        self.send_json_response({}, 200)
            else:
                self.send_json_response({}, 200)
        else:
            super().do_GET()

    def send_json_response(self, data, status=200):
        self.send_response(status)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), SimulationHandler) as httpd:
        print(f"CarbonGrid Server running at http://localhost:{PORT}")
        print("Press Ctrl+C to stop.")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            pass
